language: ruby
rvm:
- 2.2
- jruby - create - delete - update
before_install:
- openssl aes-256-cbc -K $encrypted_05b8baf07ee6_key -iv $encrypted_05b8baf07ee6_iv
  -in sa-gcp-deployer.json.enc -out sa-gcp-deployer.json -d
